### ISSUE TITLE
Videos - Missing You May Also Like Section

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#141]
The video pages are missing the may also like section.

**Comment by jindaliiita** [comment]
@colinvlasak Can you please specify the page url here for better understanding.

**Comment by colinvlasak** [comment]
@jindaliiita any of the subpages under https://main--shredit--stericycle.aem.live/en-us/resource-center/videos

e.g. https://main--shredit--stericycle.aem.live/en-us/resource-center/videos/data-breaches-understanding-todays-threats and https://main--shredit--stericycle.aem.live/en-us/resource-center/videos/hipaa-compliance-securing-your-company-s-patient-and-personal-i

**Comment by jindaliiita** [comment]
Assigning this to @dkuntze since he worked on blog page related content section

**Comment by kronnox** [comment]
Yeah, the related content section is indeed missing. This is a bit more complicated than it looks. Blogs and press releases still use an older templating system. Instead of frankinsteining the old related content system into another side, I would rather refactor that part and clean it up across all resource types.

I'll unassign for now and focus on other low hanging fruit and we'll come back to this later.
