### ISSUE TITLE
Mobile Blade Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#222]
Blade bleeding into text on mobile layouts – example https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service 

This is happening in multiple places with these layouts

![image](https://github.com/user-attachments/assets/883f72a5-fdd2-43ff-83c5-92fe9e940521)

**Comment by jindaliiita** [comment]
The same behavior as the live site is observed for screen sizes greater than 576 px. For the mobile view, I have removed the image because the live site does not have it either.
<img width="1728" alt="Screenshot 2024-09-26 at 9 53 04 PM" src="https://github.com/user-attachments/assets/22fbf394-a270-47c9-8cec-b6a4c2dd3027">
