### ISSUE TITLE
Resource Center - Content Filtering

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#393]
Content Filtering is not correct on Resource Center main page

https://main--shredit--stericycle.aem.live/en-us/resource-center

Only content being shown in Info Sheets. Should show all asset types (blogs, infographics, videos, etc.). 

![image](https://github.com/user-attachments/assets/5c4f8b10-05c6-47f0-bd6f-1271a2ab5973)

See current live site for what this should look like: https://www.shredit.com/en-us/resource-center

**Comment by jindaliiita** [comment]
@colinvlasak This issue will be fixed via https://github.com/aemsites/stericycle-shared/pull/395
But i am seeing some more issues on this page and i am not sure if this is intentional or not Like
EDS
<img width="417" alt="Screenshot 2024-10-29 at 3 14 21 PM" src="https://github.com/user-attachments/assets/64aebc74-8112-4a47-9b89-503a7060f641">

Live
<img width="440" alt="Screenshot 2024-10-29 at 3 15 42 PM" src="https://github.com/user-attachments/assets/79970498-9aaf-492d-aed1-15d72cd695a4">

**Comment by colinvlasak** [comment]
@jindaliiita thanks for flagging. The EDS site should also list the media type in the sidebar as our live site does. Please ensure that is included in the fix.

**Comment by colinvlasak** [comment]
@MarquiseRosier there are still some issues with the side bar. On https://main--shredit--stericycle.aem.live/en-us/resource-center it still only shows topic. It should also render Media type like our live site does. Also Info Sheets is listed as a topic which is incorrect. 

![image](https://github.com/user-attachments/assets/e4e4dd6f-4630-4a74-ba15-9470f6130db4)

**Comment by jindaliiita** [comment]
@colinvlasak Let me create a followup issue for this. Closing this issue

**Comment by jindaliiita** [comment]
Created https://github.com/aemsites/stericycle-shared/issues/446 as a followup issue
