### ISSUE TITLE
Home Page - Information Security Resources - Rendering Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#399]
Information Security Resources section not rendering properly

- Missing page title
- Missing content type tag
- Missing Read More Button Link

Link: https://main--shredit--stericycle.aem.live/en-us

Information Security Resources

![image](https://github.com/user-attachments/assets/5e984739-ac27-4f9a-ad8e-96dc15f484e0)

Should look like:
![image](https://github.com/user-attachments/assets/659a22c3-d35e-443b-a646-6e3f40dc21f9)

**Comment by colinvlasak** [comment]
@kronnox thanks for the info. I have added the block to the page. It only seems to be showing Blogs though even though I added other asset types. Can you confirm the logic behind this and if the set-up is correct?

**Comment by kronnox** [comment]
@colinvlasak You can configure the type and amount of posts like seen [here](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/shredit/drafts/janlucaa/post-teaser-list.docx). The type corresponds to the sheet names set up in the query-index.xls:
![Screenshot 2024-10-31 at 16 51 33](https://github.com/user-attachments/assets/8b0927f3-a198-404f-a277-3e84de8e1a32)
So in your case you can probably just use the `all-resources` type. Joining multiple types with `, ` should also work, but the `all-resources` type is more performant, since the heavy calculation can be done "server-side" in the excel sheet.

**Comment by colinvlasak** [comment]
@kronnox thanks for the tip re all resources. Updated it on the home page.
