### ISSUE TITLE
CLS within text paragraphs

### ISSUE THREAD

**Issue by kronnox** [aemsites/stericycle-shared#439]
On a few of the blog pages PSI is reporting CLS within the text content. It doesn't seem to appear every time. This needs further investigation and may need to be mitigated.

![Screenshot 2024-11-05 at 16 58 20](https://github.com/user-attachments/assets/61a5f807-e149-4af6-9729-d1cee8d189f4)

Examples:
- https://main--shredit--stericycle.aem.live/en-us/about/media-contacts
- https://main--shredit--stericycle.aem.live/en-us/blog/11-fraud-prevention-strategies-for-business
- https://main--shredit--stericycle.aem.live/en-us/blog/security-for-byod-solutions-for-workplace-concerns
- https://main--shredit--stericycle.aem.live/en-us/blog/protect-yourself-this-tax-season-top-5-tips-for-in
- https://main--shredit--stericycle.aem.live/en-us/blog/what-to-look-for-in-a-data-destruction-partner

**Comment by kronnox** [comment]
Sped som time trying to optimize the font-fallbacks, but they seem to be as good as they get already. Not sure what else we could do about this. Deferring for now

**Comment by jindaliiita** [comment]
@kronnox, I believe the CLS issue is caused by the form located at the end, which is also part of the above-the-fold content. This happens because there is no placeholder for it initially.

https://pagespeed.web.dev/analysis/https-main--shredit--stericycle-aem-live-en-us-about-media-contacts/oswa7yytjy?form_factor=mobile
