### ISSUE TITLE
About - Who We Are - Family Of Brands Image Tiny On Mobile

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#468]
On the Who We Are page Family Of Brands Image is Tiny On Mobile. Looks like it's because it's an icon. Image should render same size as other images on the page

Link: https://main--shredit--stericycle.aem.live/en-us/about/company-overview/who-we-are 

![image](https://github.com/user-attachments/assets/67c678fd-5028-4dba-94c5-904b1e68a143)

**Comment by jindaliiita** [comment]
@colinvlasak As I observe, in mobile view, we have placed the image in the first position for columns with images, even though it appears in the second column in tablet and desktop views. Is this correct? I'm unsure about the intention behind this, as it’s consistent across all pages. However this issue is fixed.

<img width="1728" alt="Screenshot 2024-11-14 at 3 28 25 PM" src="https://github.com/user-attachments/assets/03579482-b9b7-47a9-bad4-a380dca82f5f">

**Comment by jindaliiita** [comment]
Closing this as of now.

**Comment by colinvlasak** [comment]
@jindaliiita thanks for fixing this. I don't think the images need to be first for mobile even though it appears in the second column in tablet and desktop views, However if that's how it is now as is, I am fine with it. As long as it won't cause issues in the future it's okay as is.
