### ISSUE TITLE
Sustainability - Layout Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#473]
There are some layout issues on - https://main--shredit--stericycle.aem.page/en-us/about/social-responsibility/sustainability

1. Images Rendering Too Large (causes them to be blurry and take up too much real estate on the page)

![image](https://github.com/user-attachments/assets/f8466096-6d16-4715-bfe6-754e98148862)

Should look like:

![image](https://github.com/user-attachments/assets/c2420806-b27e-4753-90ef-8eef2911c241)

Is there a way that we can set image sizes within documents? 

2. Columns text not rendering centered

![image](https://github.com/user-attachments/assets/05a68bf6-01c2-4354-80c8-910fad7ff914)

Should be:
![image](https://github.com/user-attachments/assets/c7ee7baf-66f9-41ae-8ea0-733f13a06316)

**Comment by jindaliiita** [comment]
@colinvlasak  I've updated the image rendering to display in two columns. If you’d like the columns to be equal in size, we would need to modify the code, but I’ve opted not to do so, as this would introduce an additional column variant. In Edge Delivery Services, our goal is to simplify rather than add unnecessary complexity.

Also, image sizes will use their native dimensions; they can’t be adjusted within the document itself, and we don’t want authors to handle this to keep things simpler.

**Comment by jindaliiita** [comment]
Closing this as of now. Feel free to reopen this.
