### ISSUE TITLE
Assessments Wrong Labels

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#648]
Some issues on https://main--shredit--stericycle.aem.live/en-us/resource-center/assessments

The title says "Explore More Posters" it should be "Explore More Assessments"

Topic lists blogs. These are assessments should not list blogs as a tag

![image](https://github.com/user-attachments/assets/78431c37-889f-45c1-bfa3-a096be510e82)

Need to ensure the settings for all of these section type pages are accurate

**Comment by jindaliiita** [comment]
@colinvlasak I have updated the text to "Explore More Assessments" for now. You can also make these changes if needed, as it is present in the document.
Regarding the second issue, the blogs visible under the topic were due to the page [Clean Desk Policy Quiz](https://main--shredit--stericycle.aem.page/en-us/resource-center/assessments/clean-desk-policy-quiz) being incorrectly tagged as a blog. I have corrected this in the document as well.
